import "./globals.css";
import { Roboto } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";

const roboto = Roboto({
  weight: ["300", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
